version: '3.7'


volumes:
  sygnal-data:
    name: sygnal-data


services:
  sygnal:
    container_name: 'sygnal'
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: always
    volumes:
      - sygnal-data:/data
    environment:
      - SYGNAL_CONF=/data/sygnal.yaml
      - GOOGLE_APPLICATION_CREDENTIALS=/data/pocketnet-firebase-adminsdk.json
    ports:
      - "5001:5000"
